services:

  init_kafka:
    container_name: init_kafka
    build: .
    image: producer
    volumes:
      - type: bind
        source: ./init_kafka.py
        target: /app/init_kafka.py
    command: [ "./init_kafka.py"]
    networks:
      - kafka-stack-docker-compose_default

  producer:
    container_name: producer
    build: .
    image: producer
    volumes:
      - type: bind
        source: ./producer.py
        target: /app/producer.py
      - type: bind
        source: ./favorites.csv
        target: /app/favorites.csv
    command: [ "./producer.py"]
    depends_on:
      - app
    networks:
      - kafka-stack-docker-compose_default
  
  app:
    container_name: app
    build: .
    image: app
    volumes:
      - type: bind
        source: ./app.py
        target: /app/app.py
    command: [ "./app.py"]
    depends_on:
      - init_kafka
    networks:
      - kafka-stack-docker-compose_default

networks:
  kafka-stack-docker-compose_default:
    external: true
